apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qgqv9z60w-go 
  janus-idp.io/tekton: qgqv9z60w-go
  backstage.io/kubernetes-id: qgqv9z60w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qgqv9z60w-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  