apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qgqv9z60w-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qgqv9z60w-go 
  name: qgqv9z60w-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qgqv9z60w-go 
